import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(debugShowCheckedModeBanner: false, home: Main()));
}

class Main extends StatelessWidget {
  var androidVersions = [
    "الرَّحْمَنُ",
    "Allah Yang Maha Pengasih",
    "الرَّحِيمُ",
    "Allah Yang Maha Penyayang",
    "الْمَلِكُ",
    "Allah Yang Maha Merajai",
    "الْقُدُّوسُ",
    "Allah Yang Maha Suci",
    "السَّلاَمُ",
    "Allah Yang Maha Memberi Kesejahteraan",
    "الْمُؤْمِنُ",
    "Allah Yang Maha Memberi Keamanan",
    "الْمُهَيْمِنُ",
    "Allah Yang Maha Mengatur",
    "الْعَزِيزُ",
    "Allah Yang Maha Perkasa",
    "الْجَبَّارُ",
    "Allah Yang Memiliki Mutlak Kegagahan",
    "الْمُتَكَبِّرُ",
    "Allah Yang Maha Megah,Yang Memiliki Kebesaran",
    "الْخَالِقُ",
    "Allah Yang Maha Pencipta",
    "الْبَارِئُ",
    "Allah Yang Maha Melepaskan (Membuat,Membentuk, Menyeimbangkan)",
    "الْمُصَوِّرُ",
    "Allah Yang Maha Membentuk Rupa(makhluknya)",
    "الْغَفَّارُ",
    "Allah Yang Maha Pengampun",
    "الْقَهَّارُ",
    "Allah Yang Maha Menundukkan/Menaklukkan Segala Sesuatu",
    "الْوَهَّابُ",
    "Allah Yang Maha Pemberi Karunia",
    "الرَّزَّاقُ",
    "Allah Yang Maha Pemberi Rezeki",
    "الْفَتَّاحُ",
    "Allah Yang Maha Pembuka Rahmat",
    "اَلْعَلِيْمُ",
    "Allah Yang Maha Mengetahui MemilikiIlmu",
    "الْقَابِضُ",
    "Allah Yang Maha Menyempitkan makhluknya",
    "الْبَاسِطُ",
    "Allah Yang Maha Melapangkan makhluknya",
    "الْخَافِضُ",
    "Allah Yang Maha Merendahkan makhluknya",
    "الرَّافِعُ",
    "Allah Yang Maha Meninggikan makhluknya",
    "الْمُعِزُّ",
    "Allah Yang Maha Memuliakan makhluknya",
    "المُذِلُّ",
    "Allah Yang Maha Menghinakan makhluknya",
    "السَّمِيعُ",
    "Allah Yang Maha Mendengar",
    "الْبَصِيرُ",
    "Allah Yang Maha Melihat",
    "الْحَكَمُ",
    "Allah Yang Maha Menetapkan",
    "الْعَدْلُ",
    "Allah Yang Maha Adil",
    "اللَّطِيفُ",
    "Allah Yang Maha Lembut",
    "الْخَبِيرُ",
    "Allah Yang Maha Mengenal",
    "الْحَلِيمُ",
    "Allah Yang Maha Penyantun",
    "الْعَظِيمُ",
    "Allah Yang Maha Agung",
    "الْغَفُورُ",
    "Allah Yang Maha Memberi Pengampunan",
    "الشَّكُورُ",
    "Allah Yang Maha Pembalas Budi (Menghargai)",
    "الْعَلِيُّ",
    "Allah Yang Maha Tinggi",
    "الْكَبِيرُ",
    "Allah Yang Maha Besar",
    "الْحَفِيظُ",
    "Allah Yang Maha Memelihara",
    "المُقيِت",
    "Allah Yang Maha Pemberi Kecukupan",
    "الْحسِيبُ",
    "Allah Yang Maha Membuat Perhitungan",
    "الْجَلِيلُ",
    "Allah Yang Maha Luhur",
    "الْكَرِيمُ",
    "Allah Yang Maha Pemurah",
    "الرَّقِيبُ",
    "Allah Yang Maha Mengawasi",
    "الْمُجِيبُ",
    "Allah Yang Maha Mengabulkan",
    "الْوَاسِعُ",
    "Allah Yang Maha Luas",
    "الْحَكِيمُ",
    "Allah Yang Maha Bijaksana",
    "الْوَدُودُ",
    "Allah Yang Maha Mengasihi",
    "الْمَجِيدُ",
    "Allah Yang Maha Mulia",
    "الْبَاعِثُ",
    "Allah Yang Maha Membangkitkan",
    "الشَّهِيدُ",
    "Allah Yang Maha Menyaksikan",
    "الْحَقُّ",
    "Allah Yang Maha Benar",
    "الْوَكِيلُ",
    "Allah Yang Maha Memelihara",
    "الْقَوِيُّ",
    "Allah Yang Maha Kokoh",
    "الْمَتِينُ",
    "Allah Yang Maha Melindungi",
    "الْوَلِيُّ",
    "Allah Yang Maha Terpuji",
    "الْحَمِيدُ",
    "Allah Yang Maha Menghitung Segala Sesuatu",
    "الْمُحْصِي",
    "Allah Yang Maha Memulai",
    "الْمُبْدِئُ",
    "Allah Yang Maha Mengembalikan Kehidupan",
    "الْمُعِيدُ",
    "Allah Yang Maha Menghidupkan",
    "الْمُحْيِي",
    "Allah Yang Maha Mematikan",
    "اَلْمُمِيتُ",
    "Allah Yang Maha Hidup",
    "الْحَيُّ",
    "Allah Yang Maha Mandiri",
    "الْقَيُّومُ",
    "Allah Yang Maha Penemu",
    "الْوَاجِدُ",
    "Allah Yang Maha Mulia",
    "الْمَاجِدُ",
    "Allah Yang Maha Tunggal",
    "الْواحِدُ",
    "Allah Yang Maha Esa",
    "اَلاَحَدُ",
    "Allah Yang Maha Dibutuhkan-TempatMeminta",
    "الصَّمَدُ",
    "Allah Yang Maha Menentukan-Maha Menyeimbangkan",
    "الْقَادِرُ",
    "Allah Yang Maha Berkuasa",
    "الْمُقْتَدِرُ",
    "Allah Yang Maha Mendahulukan",
    "الْمُقَدِّمُ",
    "Allah Yang Maha Mengakhirkan",
    "الْمُؤَخِّرُ",
    "Allah Yang Maha Awal",
    "الأوَّلُ",
    "Allah Yang Maha Akhir",
    "الآخِرُ",
    "Allah Yang Maha Nyata",
    "الظَّاهِرُ",
    "Allah Yang Maha Ghaib",
    "الْبَاطِنُ",
    "Allah Yang Maha Memerintah",
    "الْوَالِي",
    "Allah Yang Maha Tinggi",
    "الْمُتَعَالِي",
    "Allah Yang Maha Penderma (MahaPemberi Kebajikan)",
    "الْبَرُّ",
    "Allah Yang Maha Penerima Tobat",
    "التَّوَابُ",
    "Allah Yang Maha Pemberi Balasan",
    "الْمُنْتَقِمُ",
    "Allah Yang Maha Pemaaf",
    "العَفُوُّ",
    "Allah Yang Maha Pengasuh",
    "الرَّؤُوفُ",
    "Allah Yang Maha Penguasa Kerajaan(Semesta)",
    "مَالِكُ الْمُلْكِ",
    "Allah Yang Maha Pemilik Kebesaran danKemuliaan",
    "ذُوالْجَلاَلِ وَالإكْرَام",
    "Allah Yang Maha Pemberi Keadilan",
    "الْمُقْسِطُ",
    "Allah Yang Maha Mengumpulkan",
    "الْجَامِعُ",
    "Allah Yang Maha Kaya",
    "الْغَنِيُّ",
    "Allah Yang Maha Pemberi Kekayaan",
    "الْمُغْنِي",
    "Allah Yang Maha Mencegah",
    "اَلْمَانِعُ",
    "Allah Yang Maha Penimpa Kemudharatan",
    "الضَّارَّ",
    "Allah Yang Maha Memberi Manfaat",
    "النَّافِعُ",
    "Allah Yang Maha Bercahaya (Menerangi,Memberi Cahaya)",
    "النُّورُ",
    "Allah Yang Maha Pemberi Petunjuk",
    "الْهَادِي",
    "Allah Yang Maha Pencipta Yang TiadaBandingannya",
    "الْبَدِيعُ",
    "Allah Yang Maha Kekal",
    "اَلْبَاقِي",
    "Allah Yang Maha Pewaris",
    "الْوَارِثُ",
    "Allah Yang Maha Pandai",
    "الرَّشِيدُ",
    "Allah Yang Maha Sabar",
    "الصَّبُورُ",
    "Allah Yang Maha Memberi Keamanan"
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Flutter ListView"),
      ),
      body: ListView.builder(
        itemBuilder: (context, index) {
          return Padding(
            padding: const EdgeInsets.all(8.0),
            child: Text(androidVersions[index]),
          );
        },
        itemCount: androidVersions.length,
      ),
    );
  }
}
